### ISSUE TITLE
Ability to report the full path to a failure using a flag

### ISSUE THREAD

**Issue by CaribouJohn** [pysys-test/pysys-test#34]
Problem
----------------

I am writing a vs-code extension for Pysys and I would like to take advantage of the problem matcher mechanism. 

https://code.visualstudio.com/docs/editor/tasks#:~:text=Defining%20a%20multiline%20problem%20matcher&text=js)%20with%20a%20different%20regular,line%20you%20want%20to%20match.

This is a way to define a regex to determine what errors occurred and where they actually originated. For example when you compile etc you will get a list of errors which can be listed under problems (below is simply a placeholder and will show the failure messages once fully written)

![image](https://user-images.githubusercontent.com/6026956/87729963-76426d80-c7be-11ea-8a75-e1c07b1f498d.png)

However I cannot get enough information from the Pysys output to determine the exact file I need to show when I click on the problem, and it would be more efficient to handle single lines. 

![image](https://user-images.githubusercontent.com/6026956/87730118-d3d6ba00-c7be-11ea-9f45-ae19e07a0518.png)

Solution
----------
I would like to have a runtime flag (--terse) which would output just a list of errors, this would include a full path to the run.py and contain all input on one line. 
E.G. 
23:28:50 INFO  ==============================================================
23:28:50 INFO  Id   : test05
23:28:50 INFO  ==============================================================
23:28:50 WARN  Assertion on boolean expression equal to false ... failed [run.py:6]
23:28:50 INFO  
23:28:50 INFO  Test duration: 0.01 secs
23:28:50 INFO  Test final outcome:  FAILED
23:28:50 INFO  Test outcome reason: Assertion on boolean expression equal to false
23:28:50 INFO  
23:28:50 CRIT  
23:28:50 CRIT  Completed test run at:  Thursday 2020-07-16 23:28:50 BST
23:28:50 CRIT  Total test duration:    0.02 secs

would be output as 

23:28:50, WARN, test05,  my-new-pysys-project/test05/run.py , 6 , Assertion on boolean expression equal to false, 

this would allow us (pysys vs-code extension) to navigate to the actual file and line that the failure occurs on from the problems tab (first image above). If there is no specific line it would at least allow the user to navigate to the test easily. Other errors may just be informational and can also be shown 

Because it would be behind a command line flag it would be backward compatible

**Comment by CaribouJohn** [comment]
N.B. https://github.com/CaribouJohn/pysys-vscode-extension or https://cariboujohn.github.io/pysys-vscode-extension/ 


search for pysys from vs-code to install from marketplace

**Comment by ben-spiller** [comment]
Actually it's possible to implement something like that without changes using the existing https://pysys-test.github.io/pysys-test/autodocgen/pysys.writer.html API - which you could use until a new PySys release is available. However I agree it'd be nice to have something in the box for this! 

Some questions:
1) is it more helpful for the location to be the line in the run.py that caused it, or to be the run.log since in most cases run.log is the first place people will look to get the full info on what happened? Or maybe they'll be looking in the console for the log output. Not sure... what do you think? 
2) what delimiter to use. All the obvious ones can in theory appear inside a path : , () ; Maybe : is best? (and we can special-case the windows [driveletter}: prefix in the regex)
3) what kind of slashes to use - OS-dependent slashes OK? Probably?
4) what format to use for the message. Might be best to use a format that other popular tools use for maximum reuse. e.g. 

  make - file:line: error: msg
  Visual Studio - file(line): error ERRORCODE: msg

I'm tempted by the "make" format which is more widely used?

**Comment by ben-spiller** [comment]
See above commit - will this do what you need? It's triggered by an env var rather than cmd line option, which would allow you to provide a different format if you wish to e.g. you coudl have a PySys_VSCode: prefix on the lines, or whatever you like. Or just use the default which is make-style. This generates "error" for failures, and "warning" for outcomes NOTVERIFIED (and nothing for passed/inspect/skipped)

**Comment by CaribouJohn** [comment]
Sorry Ben been busy around the house only just got back to this - thats interesting actually I will look into the writer and check out the changes you made. I will try to get this into a release today if possible - I think it will be good :)
